# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Samrath49/AI-with-Tensorflow/blob/master/College%20Lab.ipynb
"""

import pandas as pd #used to convert unstructured data into tabuler form structured data
import numpy as np # it means numbers in python for numbers
import seaborn as sns # seaboen includes extra graphical functions that r not there in matplot lib
import matplotlib.pyplot as mp # mathematical ploting using graphs ets

data = {'Sno': [1,2,3,4,5,6,7,8,9,10],
        'Horse_Id': ['H01','H02','H03','H04','H05','H06','H07','H08','H09','H10'],
        'Horse_Gender': ['M','F','F','F','M','M','F','F','M','F'],
        'Horse_Height(cm)':[188,190,178,150,np.NaN,198,200,179,np.NaN,180],
        'Horse_Weight(kg)':[410,550,600,710,590,630,np.NaN,740,650,720],
        'Racer_Horse':['yes','no','yes','no','yes','no','yes','no','yes','no']}

df = pd.DataFrame(data,columns=['Sno','Horse_Id', 'Horse_Gender', 'Horse_Height(cm)','Horse_Weight(kg)','Racer_Horse'])

df # data in tabular form as sorted data is called dataframe

info = df.dropna()
info

df.head(2)

df.tail(2)

df.info()

df.loc[(df['Horse_Height(cm)'].isnull()),'Horse_Height(cm)'] = df['Horse_Height(cm)'].mean()

df.loc[(df['Horse_Gender']=='F')&(df['Horse_Weight(kg)'].isnull()),'Horse_Weight(kg)'] = 550

df

target = df['Racer_Horse']
target

df=df.drop(['Horse_Id'],axis=1)

df

df.hist()

sns.pairplot(df)

sns.pairplot(df,hue="Racer_Horse")

sns.boxplot(x="Horse_Height(cm)", y="Racer_Horse",data=df)

sns.boxplot(x="Horse_Height(cm)", y="Horse_Gender",data=df)

sns.violinplot(x="Horse_Height(cm)",y="Racer_Horse",data=df)

sns.violinplot(x="Horse_Height(cm)",y="Racer_Horse",data=df, inner="quartile")